/*
Weather Observation Station 1

Query a list of CITY and STATE from the STATION table.

Input Format

The STATION table is described as follows:

+--------+--------------+
| FILEDS |     TYPE     |
+--------+--------------+
| ID     | NUMBER       |
| CITY   | VARCHAR2(21) |
| STATE  | VARCHAR2(2)  |
| LAT_N  | NUMBER       |
| LONG_W | NUMBER       |
+--------+--------------+

where LAT_N is the northern latitude and LONG_W is the western longitude.
*/

use hackerrank;

GO

raiserror('Now at the create procedure section ....',0,1)

GO

CREATE or ALTER PROCEDURE basicselect.proc_07wos01 AS
select 
	CITY, 
	STATE 
from 
	basicselect.STATION;
GO

CREATE or ALTER PROCEDURE BasicSelectTestClass.test_07wos01 AS
BEGIN
    IF OBJECT_ID('actual') IS NOT NULL DROP TABLE actual;
    IF OBJECT_ID('expected') IS NOT NULL DROP TABLE expected;

	CREATE TABLE actual (
	   CITY           varchar(21),
	   STATE		  varchar(2)
    );

    INSERT INTO actual (CITY, STATE) exec basicselect.proc_07wos01

    CREATE TABLE expected (
	   CITY           varchar(21),
	   STATE		  varchar(2)
    );

	INSERT INTO expected (CITY, STATE) select 'Kissee Mills','MO'
	INSERT INTO expected (CITY, STATE) select 'Loma Mar','CA'
	INSERT INTO expected (CITY, STATE) select 'Sandy Hook','CT'
	INSERT INTO expected (CITY, STATE) select 'Tipton','IN'
	INSERT INTO expected (CITY, STATE) select 'Arlington','CO'
	INSERT INTO expected (CITY, STATE) select 'Turner','AR'
	INSERT INTO expected (CITY, STATE) select 'Slidell','LA'
	INSERT INTO expected (CITY, STATE) select 'Negreet','LA'
	INSERT INTO expected (CITY, STATE) select 'Glencoe','KY'
	INSERT INTO expected (CITY, STATE) select 'Chelsea','IA'
	INSERT INTO expected (CITY, STATE) select 'Chignik Lagoon','AK'
	INSERT INTO expected (CITY, STATE) select 'Pelahatchie','MS'
	INSERT INTO expected (CITY, STATE) select 'Hanna City','IL'
	INSERT INTO expected (CITY, STATE) select 'Dorrance','KS'
	INSERT INTO expected (CITY, STATE) select 'Albany','CA'
	INSERT INTO expected (CITY, STATE) select 'Monument','KS'
	INSERT INTO expected (CITY, STATE) select 'Manchester','MD'
	INSERT INTO expected (CITY, STATE) select 'Prescott','IA'
	INSERT INTO expected (CITY, STATE) select 'Graettinger','IA'
	INSERT INTO expected (CITY, STATE) select 'Cahone','CO'
	INSERT INTO expected (CITY, STATE) select 'Sturgis','MS'
	INSERT INTO expected (CITY, STATE) select 'Upperco','MD'
	INSERT INTO expected (CITY, STATE) select 'Highwood','IL'
	INSERT INTO expected (CITY, STATE) select 'Waipahu','HI'
	INSERT INTO expected (CITY, STATE) select 'Bowdon','GA'
	INSERT INTO expected (CITY, STATE) select 'Tyler','MN'
	INSERT INTO expected (CITY, STATE) select 'Watkins','CO'
	INSERT INTO expected (CITY, STATE) select 'Republic','MI'
	INSERT INTO expected (CITY, STATE) select 'Millville','CA'
	INSERT INTO expected (CITY, STATE) select 'Aguanga','CA'
	INSERT INTO expected (CITY, STATE) select 'Bowdon Junction','GA'
	INSERT INTO expected (CITY, STATE) select 'Morenci','AZ'
	INSERT INTO expected (CITY, STATE) select 'South El Monte','CA'
	INSERT INTO expected (CITY, STATE) select 'Hoskinston','KY'
	INSERT INTO expected (CITY, STATE) select 'Talbert','KY'
	INSERT INTO expected (CITY, STATE) select 'Mccomb','MS'
	INSERT INTO expected (CITY, STATE) select 'Kirk','CO'
	INSERT INTO expected (CITY, STATE) select 'Carlock','IL'
	INSERT INTO expected (CITY, STATE) select 'Seward','IL'
	INSERT INTO expected (CITY, STATE) select 'Gustine','CA'
	INSERT INTO expected (CITY, STATE) select 'Delano','CA'
	INSERT INTO expected (CITY, STATE) select 'Westphalia','MI'
	INSERT INTO expected (CITY, STATE) select 'Saint Elmo','AL'
	INSERT INTO expected (CITY, STATE) select 'Roy','MT'
	INSERT INTO expected (CITY, STATE) select 'Pattonsburg','MO'
	INSERT INTO expected (CITY, STATE) select 'Centertown','MO'
	INSERT INTO expected (CITY, STATE) select 'Norvell','MI'
	INSERT INTO expected (CITY, STATE) select 'Raymondville','MO'
	INSERT INTO expected (CITY, STATE) select 'Beaver Island','MI'
	INSERT INTO expected (CITY, STATE) select 'Odin','IL'
	INSERT INTO expected (CITY, STATE) select 'Jemison','AL'
	INSERT INTO expected (CITY, STATE) select 'West Hills','CA'
	INSERT INTO expected (CITY, STATE) select 'Barrigada','GU'
	INSERT INTO expected (CITY, STATE) select 'Hesperia','CA'
	INSERT INTO expected (CITY, STATE) select 'Wickliffe','KY'
	INSERT INTO expected (CITY, STATE) select 'Culdesac','ID'
	INSERT INTO expected (CITY, STATE) select 'Roselawn','IN'
	INSERT INTO expected (CITY, STATE) select 'Forest Lakes','AZ'
	INSERT INTO expected (CITY, STATE) select 'San Simeon','CA'
	INSERT INTO expected (CITY, STATE) select 'Little Rock','AR'
	INSERT INTO expected (CITY, STATE) select 'Portland','AR'
	INSERT INTO expected (CITY, STATE) select 'New Century','KS'
	INSERT INTO expected (CITY, STATE) select 'Hampden','MA'
	INSERT INTO expected (CITY, STATE) select 'Pine City','MN'
	INSERT INTO expected (CITY, STATE) select 'Sandborn','IN'
	INSERT INTO expected (CITY, STATE) select 'Seaton','IL'
	INSERT INTO expected (CITY, STATE) select 'Milledgeville','IL'
	INSERT INTO expected (CITY, STATE) select 'East China','MI'
	INSERT INTO expected (CITY, STATE) select 'Prince Frederick','MD'
	INSERT INTO expected (CITY, STATE) select 'Pomona Park','FL'
	INSERT INTO expected (CITY, STATE) select 'Gretna','LA'
	INSERT INTO expected (CITY, STATE) select 'Yazoo City','MS'
	INSERT INTO expected (CITY, STATE) select 'Zionsville','IN'
	INSERT INTO expected (CITY, STATE) select 'Rio Oso','CA'
	INSERT INTO expected (CITY, STATE) select 'Jolon','CA'
	INSERT INTO expected (CITY, STATE) select 'Childs','MD'
	INSERT INTO expected (CITY, STATE) select 'Shreveport','LA'
	INSERT INTO expected (CITY, STATE) select 'Forest','MS'
	INSERT INTO expected (CITY, STATE) select 'Sizerock','KY'
	INSERT INTO expected (CITY, STATE) select 'Buffalo Creek','CO'
	INSERT INTO expected (CITY, STATE) select 'Algonac','MI'
	INSERT INTO expected (CITY, STATE) select 'Onaway','MI'
	INSERT INTO expected (CITY, STATE) select 'Irvington','IL'
	INSERT INTO expected (CITY, STATE) select 'Winsted','MN'
	INSERT INTO expected (CITY, STATE) select 'Woodbury','GA'
	INSERT INTO expected (CITY, STATE) select 'Samantha','AL'
	INSERT INTO expected (CITY, STATE) select 'Hackleburg','AL'
	INSERT INTO expected (CITY, STATE) select 'Soldier','KS'
	INSERT INTO expected (CITY, STATE) select 'Arrowsmith','IL'
	INSERT INTO expected (CITY, STATE) select 'Columbus','GA'
	INSERT INTO expected (CITY, STATE) select 'Bentonville','AR'
	INSERT INTO expected (CITY, STATE) select 'Kirkland','AZ'
	INSERT INTO expected (CITY, STATE) select 'Grosse Pointe','MI'
	INSERT INTO expected (CITY, STATE) select 'Wilton','ME'
	INSERT INTO expected (CITY, STATE) select 'Busby','MT'
	INSERT INTO expected (CITY, STATE) select 'Robertsdale','AL'
	INSERT INTO expected (CITY, STATE) select 'Dale','IN'
	INSERT INTO expected (CITY, STATE) select 'Reeds','MO'
	INSERT INTO expected (CITY, STATE) select 'Hayfork','CA'
	INSERT INTO expected (CITY, STATE) select 'Mcbrides','MI'
	INSERT INTO expected (CITY, STATE) select 'Lee Center','IL'
	INSERT INTO expected (CITY, STATE) select 'Tennessee','IL'
	INSERT INTO expected (CITY, STATE) select 'Henderson','IA'
	INSERT INTO expected (CITY, STATE) select 'Udall','KS'
	INSERT INTO expected (CITY, STATE) select 'Palm Desert','CA'
	INSERT INTO expected (CITY, STATE) select 'Benedict','KS'
	INSERT INTO expected (CITY, STATE) select 'Oakfield','ME'
	INSERT INTO expected (CITY, STATE) select 'Tamms','IL'
	INSERT INTO expected (CITY, STATE) select 'Haubstadt','IN'
	INSERT INTO expected (CITY, STATE) select 'Chokio','MN'
	INSERT INTO expected (CITY, STATE) select 'Clancy','MT'
	INSERT INTO expected (CITY, STATE) select 'Scotts Valley','CA'
	INSERT INTO expected (CITY, STATE) select 'Norwood','MN'
	INSERT INTO expected (CITY, STATE) select 'Elkton','MD'
	INSERT INTO expected (CITY, STATE) select 'Bertha','MN'
	INSERT INTO expected (CITY, STATE) select 'Bridgeport','MI'
	INSERT INTO expected (CITY, STATE) select 'Cherry','IL'
	INSERT INTO expected (CITY, STATE) select 'Regina','KY'
	INSERT INTO expected (CITY, STATE) select 'Griffin','GA'
	INSERT INTO expected (CITY, STATE) select 'Pine Bluff','AR'
	INSERT INTO expected (CITY, STATE) select 'Mascotte','FL'
	INSERT INTO expected (CITY, STATE) select 'Baldwin','MD'
	INSERT INTO expected (CITY, STATE) select 'Netawaka','KS'
	INSERT INTO expected (CITY, STATE) select 'East Irvine','CA'
	INSERT INTO expected (CITY, STATE) select 'Pony','MT'
	INSERT INTO expected (CITY, STATE) select 'Franklin','LA'
	INSERT INTO expected (CITY, STATE) select 'Amo','IN'
	INSERT INTO expected (CITY, STATE) select 'Vulcan','MO'
	INSERT INTO expected (CITY, STATE) select 'Prairie Du Rocher','IL'
	INSERT INTO expected (CITY, STATE) select 'Alanson','MI'
	INSERT INTO expected (CITY, STATE) select 'Delta','LA'
	INSERT INTO expected (CITY, STATE) select 'Carver','MN'
	INSERT INTO expected (CITY, STATE) select 'Paron','AR'
	INSERT INTO expected (CITY, STATE) select 'Winchester','ID'
	INSERT INTO expected (CITY, STATE) select 'Jerome','AZ'
	INSERT INTO expected (CITY, STATE) select 'Baton Rouge','LA'
	INSERT INTO expected (CITY, STATE) select 'Greenview','CA'
	INSERT INTO expected (CITY, STATE) select 'Lucerne Valley','CA'
	INSERT INTO expected (CITY, STATE) select 'Cromwell','MN'
	INSERT INTO expected (CITY, STATE) select 'Quinter','KS'
	INSERT INTO expected (CITY, STATE) select 'Whitewater','MO'
	INSERT INTO expected (CITY, STATE) select 'Round Pond','ME'
	INSERT INTO expected (CITY, STATE) select 'Clarkdale','AZ'
	INSERT INTO expected (CITY, STATE) select 'Rockton','IL'
	INSERT INTO expected (CITY, STATE) select 'Pheba','MS'
	INSERT INTO expected (CITY, STATE) select 'Eleele','HI'
	INSERT INTO expected (CITY, STATE) select 'Auburn','IA'
	INSERT INTO expected (CITY, STATE) select 'North Berwick','ME'
	INSERT INTO expected (CITY, STATE) select 'Oconee','GA'
	INSERT INTO expected (CITY, STATE) select 'Grandville','MI'
	INSERT INTO expected (CITY, STATE) select 'Susanville','CA'
	INSERT INTO expected (CITY, STATE) select 'Rosie','AR'
	INSERT INTO expected (CITY, STATE) select 'Verona','MO'
	INSERT INTO expected (CITY, STATE) select 'Richland','GA'
	INSERT INTO expected (CITY, STATE) select 'Fremont','MI'
	INSERT INTO expected (CITY, STATE) select 'Philipsburg','MT'
	INSERT INTO expected (CITY, STATE) select 'Kensett','IA'
	INSERT INTO expected (CITY, STATE) select 'De Tour Village','MI'
	INSERT INTO expected (CITY, STATE) select 'Koleen','IN'
	INSERT INTO expected (CITY, STATE) select 'Winslow','IL'
	INSERT INTO expected (CITY, STATE) select 'Reasnor','IA'
	INSERT INTO expected (CITY, STATE) select 'West Grove','IA'
	INSERT INTO expected (CITY, STATE) select 'Frankfort Heights','IL'
	INSERT INTO expected (CITY, STATE) select 'Bono','AR'
	INSERT INTO expected (CITY, STATE) select 'Biggsville','IL'
	INSERT INTO expected (CITY, STATE) select 'Linthicum Heights','MD'
	INSERT INTO expected (CITY, STATE) select 'Amazonia','MO'
	INSERT INTO expected (CITY, STATE) select 'Marysville','MI'
	INSERT INTO expected (CITY, STATE) select 'Cape Girardeau','MO'
	INSERT INTO expected (CITY, STATE) select 'Pengilly','MN'
	INSERT INTO expected (CITY, STATE) select 'Newton Center','MA'
	INSERT INTO expected (CITY, STATE) select 'Crane Lake','MN'
	INSERT INTO expected (CITY, STATE) select 'Newbury','MA'
	INSERT INTO expected (CITY, STATE) select 'Kismet','KS'
	INSERT INTO expected (CITY, STATE) select 'Canton','ME'
	INSERT INTO expected (CITY, STATE) select 'Clipper Mills','CA'
	INSERT INTO expected (CITY, STATE) select 'Grayslake','IL'
	INSERT INTO expected (CITY, STATE) select 'Pierre Part','LA'
	INSERT INTO expected (CITY, STATE) select 'Bison','KS'
	INSERT INTO expected (CITY, STATE) select 'Bellevue','KY'
	INSERT INTO expected (CITY, STATE) select 'Ridgway','CO'
	INSERT INTO expected (CITY, STATE) select 'South Britain','CT'
	INSERT INTO expected (CITY, STATE) select 'Rydal','GA'
	INSERT INTO expected (CITY, STATE) select 'Lynnville','KY'
	INSERT INTO expected (CITY, STATE) select 'Deerfield','MO'
	INSERT INTO expected (CITY, STATE) select 'Montreal','MO'
	INSERT INTO expected (CITY, STATE) select 'Hope','MN'
	INSERT INTO expected (CITY, STATE) select 'Aliso Viejo','CA'
	INSERT INTO expected (CITY, STATE) select 'Gowrie','IA'
	INSERT INTO expected (CITY, STATE) select 'Andersonville','GA'
	INSERT INTO expected (CITY, STATE) select 'Knob Lick','KY'
	INSERT INTO expected (CITY, STATE) select 'Crouseville','ME'
	INSERT INTO expected (CITY, STATE) select 'Cranks','KY'
	INSERT INTO expected (CITY, STATE) select 'Rives Junction','MI'
	INSERT INTO expected (CITY, STATE) select 'Ledyard','CT'
	INSERT INTO expected (CITY, STATE) select 'Norway','ME'
	INSERT INTO expected (CITY, STATE) select 'Eros','LA'
	INSERT INTO expected (CITY, STATE) select 'Rantoul','KS'
	INSERT INTO expected (CITY, STATE) select 'Richmond Hill','GA'
	INSERT INTO expected (CITY, STATE) select 'Fredericktown','MO'
	INSERT INTO expected (CITY, STATE) select 'Arkadelphia','AR'
	INSERT INTO expected (CITY, STATE) select 'Glen Carbon','IL'
	INSERT INTO expected (CITY, STATE) select 'Fredericksburg','IN'
	INSERT INTO expected (CITY, STATE) select 'Manchester','IA'
	INSERT INTO expected (CITY, STATE) select 'Mc Henry','MD'
	INSERT INTO expected (CITY, STATE) select 'Eriline','KY'
	INSERT INTO expected (CITY, STATE) select 'Wellington','KY'
	INSERT INTO expected (CITY, STATE) select 'Hoffman Estates','IL'
	INSERT INTO expected (CITY, STATE) select 'Howard Lake','MN'
	INSERT INTO expected (CITY, STATE) select 'Edgewater','MD'
	INSERT INTO expected (CITY, STATE) select 'Ducor','CA'
	INSERT INTO expected (CITY, STATE) select 'Salem','KY'
	INSERT INTO expected (CITY, STATE) select 'Sturdivant','MO'
	INSERT INTO expected (CITY, STATE) select 'Hagatna','GU'
	INSERT INTO expected (CITY, STATE) select 'East Haddam','CT'
	INSERT INTO expected (CITY, STATE) select 'Eastlake','MI'
	INSERT INTO expected (CITY, STATE) select 'Larkspur','CA'
	INSERT INTO expected (CITY, STATE) select 'Patriot','IN'
	INSERT INTO expected (CITY, STATE) select 'Corriganville','MD'
	INSERT INTO expected (CITY, STATE) select 'Carlos','MN'
	INSERT INTO expected (CITY, STATE) select 'Addison','MI'
	INSERT INTO expected (CITY, STATE) select 'Tarzana','CA'
	INSERT INTO expected (CITY, STATE) select 'Grapevine','AR'
	INSERT INTO expected (CITY, STATE) select 'Kanorado','KS'
	INSERT INTO expected (CITY, STATE) select 'Climax','MI'
	INSERT INTO expected (CITY, STATE) select 'Curdsville','KY'
	INSERT INTO expected (CITY, STATE) select 'Southport','CT'
	INSERT INTO expected (CITY, STATE) select 'Compton','IL'
	INSERT INTO expected (CITY, STATE) select 'Notasulga','AL'
	INSERT INTO expected (CITY, STATE) select 'Rumsey','KY'
	INSERT INTO expected (CITY, STATE) select 'Rogers','CT'
	INSERT INTO expected (CITY, STATE) select 'Pleasant Grove','AR'
	INSERT INTO expected (CITY, STATE) select 'Everton','MO'
	INSERT INTO expected (CITY, STATE) select 'Skanee','MI'
	INSERT INTO expected (CITY, STATE) select 'Springerville','AZ'
	INSERT INTO expected (CITY, STATE) select 'Libertytown','MD'
	INSERT INTO expected (CITY, STATE) select 'Church Creek','MD'
	INSERT INTO expected (CITY, STATE) select 'Yellow Pine','ID'
	INSERT INTO expected (CITY, STATE) select 'Dumont','MN'
	INSERT INTO expected (CITY, STATE) select 'Gales Ferry','CT'
	INSERT INTO expected (CITY, STATE) select 'Ravenna','KY'
	INSERT INTO expected (CITY, STATE) select 'Williams','AZ'
	INSERT INTO expected (CITY, STATE) select 'Decatur','MI'
	INSERT INTO expected (CITY, STATE) select 'Holbrook','AZ'
	INSERT INTO expected (CITY, STATE) select 'Sherrill','AR'
	INSERT INTO expected (CITY, STATE) select 'Brownsdale','MN'
	INSERT INTO expected (CITY, STATE) select 'Linden','MI'
	INSERT INTO expected (CITY, STATE) select 'Sedgwick','AR'
	INSERT INTO expected (CITY, STATE) select 'Fort Atkinson','IA'
	INSERT INTO expected (CITY, STATE) select 'Peachtree City','GA'
	INSERT INTO expected (CITY, STATE) select 'Rocheport','MO'
	INSERT INTO expected (CITY, STATE) select 'West Somerset','KY'
	INSERT INTO expected (CITY, STATE) select 'Clovis','CA'
	INSERT INTO expected (CITY, STATE) select 'Heyburn','ID'
	INSERT INTO expected (CITY, STATE) select 'Peabody','KS'
	INSERT INTO expected (CITY, STATE) select 'Marion Junction','AL'
	INSERT INTO expected (CITY, STATE) select 'Randall','KS'
	INSERT INTO expected (CITY, STATE) select 'Hayesville','IA'
	INSERT INTO expected (CITY, STATE) select 'Jordan','MN'
	INSERT INTO expected (CITY, STATE) select 'White Horse Beach','MA'
	INSERT INTO expected (CITY, STATE) select 'Greenville','IL'
	INSERT INTO expected (CITY, STATE) select 'Macy','IN'
	INSERT INTO expected (CITY, STATE) select 'Flowood','MS'
	INSERT INTO expected (CITY, STATE) select 'Deep River','IA'
	INSERT INTO expected (CITY, STATE) select 'Napoleon','IN'
	INSERT INTO expected (CITY, STATE) select 'Leavenworth','IN'
	INSERT INTO expected (CITY, STATE) select 'Coldwater','KS'
	INSERT INTO expected (CITY, STATE) select 'Weldon','CA'
	INSERT INTO expected (CITY, STATE) select 'Yellville','AR'
	INSERT INTO expected (CITY, STATE) select 'Turners Falls','MA'
	INSERT INTO expected (CITY, STATE) select 'Delray Beach','FL'
	INSERT INTO expected (CITY, STATE) select 'Eustis','FL'
	INSERT INTO expected (CITY, STATE) select 'Mineral Point','MO'
	INSERT INTO expected (CITY, STATE) select 'Weldona','CO'
	INSERT INTO expected (CITY, STATE) select 'Midpines','CA'
	INSERT INTO expected (CITY, STATE) select 'Cascade','ID'
	INSERT INTO expected (CITY, STATE) select 'Tefft','IN'
	INSERT INTO expected (CITY, STATE) select 'Showell','MD'
	INSERT INTO expected (CITY, STATE) select 'Bayville','ME'
	INSERT INTO expected (CITY, STATE) select 'Brighton','IL'
	INSERT INTO expected (CITY, STATE) select 'Grimes','IA'
	INSERT INTO expected (CITY, STATE) select 'Nubieber','CA'
	INSERT INTO expected (CITY, STATE) select 'North Monmouth','ME'
	INSERT INTO expected (CITY, STATE) select 'Harmony','MN'
	INSERT INTO expected (CITY, STATE) select 'Beaufort','MO'
	INSERT INTO expected (CITY, STATE) select 'Arispe','IA'
	INSERT INTO expected (CITY, STATE) select 'Union Star','MO'
	INSERT INTO expected (CITY, STATE) select 'Humeston','IA'
	INSERT INTO expected (CITY, STATE) select 'Baileyville','IL'
	INSERT INTO expected (CITY, STATE) select 'Lakeville','CT'
	INSERT INTO expected (CITY, STATE) select 'Firebrick','KY'
	INSERT INTO expected (CITY, STATE) select 'Pico Rivera','CA'
	INSERT INTO expected (CITY, STATE) select 'Ludington','MI'
	INSERT INTO expected (CITY, STATE) select 'Channing','MI'
	INSERT INTO expected (CITY, STATE) select 'West Baden Springs','IN'
	INSERT INTO expected (CITY, STATE) select 'Pawnee','IL'
	INSERT INTO expected (CITY, STATE) select 'Melber','KY'
	INSERT INTO expected (CITY, STATE) select 'Manchester','MN'
	INSERT INTO expected (CITY, STATE) select 'Bainbridge','GA'
	INSERT INTO expected (CITY, STATE) select 'Sanders','AZ'
	INSERT INTO expected (CITY, STATE) select 'Ottertail','MN'
	INSERT INTO expected (CITY, STATE) select 'Dupo','IL'
	INSERT INTO expected (CITY, STATE) select 'Montrose','CA'
	INSERT INTO expected (CITY, STATE) select 'Schleswig','IA'
	INSERT INTO expected (CITY, STATE) select 'Harbor Springs','MI'
	INSERT INTO expected (CITY, STATE) select 'Richmond','IL'
	INSERT INTO expected (CITY, STATE) select 'Ermine','KY'
	INSERT INTO expected (CITY, STATE) select 'Siler','KY'
	INSERT INTO expected (CITY, STATE) select 'Reeves','LA'
	INSERT INTO expected (CITY, STATE) select 'Clifton','AZ'
	INSERT INTO expected (CITY, STATE) select 'Casco','MI'
	INSERT INTO expected (CITY, STATE) select 'Sturgis','MI'
	INSERT INTO expected (CITY, STATE) select 'Crescent City','FL'
	INSERT INTO expected (CITY, STATE) select 'Madisonville','LA'
	INSERT INTO expected (CITY, STATE) select 'Albion','IN'
	INSERT INTO expected (CITY, STATE) select 'Lismore','MN'
	INSERT INTO expected (CITY, STATE) select 'Athens','IN'
	INSERT INTO expected (CITY, STATE) select 'Eufaula','AL'
	INSERT INTO expected (CITY, STATE) select 'Panther Burn','MS'
	INSERT INTO expected (CITY, STATE) select 'Hanscom Afb','MA'
	INSERT INTO expected (CITY, STATE) select 'Wildie','KY'
	INSERT INTO expected (CITY, STATE) select 'Mosca','CO'
	INSERT INTO expected (CITY, STATE) select 'Bennington','IN'
	INSERT INTO expected (CITY, STATE) select 'Lottie','LA'
	INSERT INTO expected (CITY, STATE) select 'Garland','ME'
	INSERT INTO expected (CITY, STATE) select 'Clutier','IA'
	INSERT INTO expected (CITY, STATE) select 'Lupton','MI'
	INSERT INTO expected (CITY, STATE) select 'Northfield','MN'
	INSERT INTO expected (CITY, STATE) select 'Daleville','AL'
	INSERT INTO expected (CITY, STATE) select 'Osage City','KS'
	INSERT INTO expected (CITY, STATE) select 'Cuba','MO'
	INSERT INTO expected (CITY, STATE) select 'Norris','MT'
	INSERT INTO expected (CITY, STATE) select 'Clopton','AL'
	INSERT INTO expected (CITY, STATE) select 'Renville','MN'
	INSERT INTO expected (CITY, STATE) select 'Saint Paul','KS'
	INSERT INTO expected (CITY, STATE) select 'Kirksville','MO'
	INSERT INTO expected (CITY, STATE) select 'Kingsland','AR'
	INSERT INTO expected (CITY, STATE) select 'Fairview','KS'
	INSERT INTO expected (CITY, STATE) select 'Lydia','LA'
	INSERT INTO expected (CITY, STATE) select 'Bridgton','ME'
	INSERT INTO expected (CITY, STATE) select 'Brownstown','IL'
	INSERT INTO expected (CITY, STATE) select 'Monona','IA'
	INSERT INTO expected (CITY, STATE) select 'Hartland','MI'
	INSERT INTO expected (CITY, STATE) select 'Andover','CT'
	INSERT INTO expected (CITY, STATE) select 'Lakota','IA'
	INSERT INTO expected (CITY, STATE) select 'Grand Terrace','CA'
	INSERT INTO expected (CITY, STATE) select 'Mesick','MI'
	INSERT INTO expected (CITY, STATE) select 'Dryden','MI'
	INSERT INTO expected (CITY, STATE) select 'Beverly','KY'
	INSERT INTO expected (CITY, STATE) select 'Marine On Saint Croix','MN'
	INSERT INTO expected (CITY, STATE) select 'Pocahontas','IL'
	INSERT INTO expected (CITY, STATE) select 'Fort Meade','FL'
	INSERT INTO expected (CITY, STATE) select 'Hayneville','AL'
	INSERT INTO expected (CITY, STATE) select 'Yoder','IN'
	INSERT INTO expected (CITY, STATE) select 'Gatewood','MO'
	INSERT INTO expected (CITY, STATE) select 'Madden','MS'
	INSERT INTO expected (CITY, STATE) select 'Losantville','IN'
	INSERT INTO expected (CITY, STATE) select 'Cheswold','DE'
	INSERT INTO expected (CITY, STATE) select 'Caseville','MI'
	INSERT INTO expected (CITY, STATE) select 'Pomona','MO'
	INSERT INTO expected (CITY, STATE) select 'Hopkinsville','KY'
	INSERT INTO expected (CITY, STATE) select 'Jack','AL'
	INSERT INTO expected (CITY, STATE) select 'Dixie','GA'
	INSERT INTO expected (CITY, STATE) select 'Hillside','CO'
	INSERT INTO expected (CITY, STATE) select 'Hawarden','IA'
	INSERT INTO expected (CITY, STATE) select 'Cannonsburg','MI'
	INSERT INTO expected (CITY, STATE) select 'Osborne','KS'
	INSERT INTO expected (CITY, STATE) select 'Elm Grove','LA'
	INSERT INTO expected (CITY, STATE) select 'Atlantic Mine','MI'
	INSERT INTO expected (CITY, STATE) select 'North Branford','CT'
	INSERT INTO expected (CITY, STATE) select 'New Liberty','IA'
	INSERT INTO expected (CITY, STATE) select 'Woodstock Valley','CT'
	INSERT INTO expected (CITY, STATE) select 'Farmington','IL'
	INSERT INTO expected (CITY, STATE) select 'Honolulu','HI'
	INSERT INTO expected (CITY, STATE) select 'Pfeifer','KS'
	INSERT INTO expected (CITY, STATE) select 'Oshtemo','MI'
	INSERT INTO expected (CITY, STATE) select 'Gridley','KS'
	INSERT INTO expected (CITY, STATE) select 'Fulton','KY'
	INSERT INTO expected (CITY, STATE) select 'Winter Park','FL'
	INSERT INTO expected (CITY, STATE) select 'Monroe','LA'
	INSERT INTO expected (CITY, STATE) select 'Del Mar','CA'
	INSERT INTO expected (CITY, STATE) select 'Greens Fork','IN'
	INSERT INTO expected (CITY, STATE) select 'Garden City','AL'
	INSERT INTO expected (CITY, STATE) select 'Blue River','KY'
	INSERT INTO expected (CITY, STATE) select 'New Ross','IN'
	INSERT INTO expected (CITY, STATE) select 'Brilliant','AL'
	INSERT INTO expected (CITY, STATE) select 'Archie','MO'
	INSERT INTO expected (CITY, STATE) select 'Winslow','AR'
	INSERT INTO expected (CITY, STATE) select 'Olmitz','KS'
	INSERT INTO expected (CITY, STATE) select 'Allerton','IA'
	INSERT INTO expected (CITY, STATE) select 'Norphlet','AR'
	INSERT INTO expected (CITY, STATE) select 'Mechanic Falls','ME'
	INSERT INTO expected (CITY, STATE) select 'North Middletown','KY'
	INSERT INTO expected (CITY, STATE) select 'Keyes','CA'
	INSERT INTO expected (CITY, STATE) select 'Equality','AL'
	INSERT INTO expected (CITY, STATE) select 'Neon','KY'
	INSERT INTO expected (CITY, STATE) select 'Calhoun','KY'
	INSERT INTO expected (CITY, STATE) select 'Alpine','AR'
	INSERT INTO expected (CITY, STATE) select 'Mullan','ID'
	INSERT INTO expected (CITY, STATE) select 'Coalgood','KY'
	INSERT INTO expected (CITY, STATE) select 'Walnut','MS'
	INSERT INTO expected (CITY, STATE) select 'Saint Petersburg','FL'
	INSERT INTO expected (CITY, STATE) select 'Ojai','CA'
	INSERT INTO expected (CITY, STATE) select 'Julian','CA'
	INSERT INTO expected (CITY, STATE) select 'Veedersburg','IN'
	INSERT INTO expected (CITY, STATE) select 'Orange Park','FL'
	INSERT INTO expected (CITY, STATE) select 'Payson','AZ'
	INSERT INTO expected (CITY, STATE) select 'Windom','KS'
	INSERT INTO expected (CITY, STATE) select 'Urbana','IA'
	INSERT INTO expected (CITY, STATE) select 'Ludlow','CA'
	INSERT INTO expected (CITY, STATE) select 'Lindsay','MT'
	INSERT INTO expected (CITY, STATE) select 'Palatka','FL'
	INSERT INTO expected (CITY, STATE) select 'Bristol','ME'
	INSERT INTO expected (CITY, STATE) select 'Harmony','IN'
	INSERT INTO expected (CITY, STATE) select 'Ukiah','CA'
	INSERT INTO expected (CITY, STATE) select 'Yuma','AZ'
	INSERT INTO expected (CITY, STATE) select 'Alba','MI'
	INSERT INTO expected (CITY, STATE) select 'Zachary','LA'
	INSERT INTO expected (CITY, STATE) select 'Esmond','IL'
	INSERT INTO expected (CITY, STATE) select 'Waresboro','GA'
	INSERT INTO expected (CITY, STATE) select 'Hills','MN'
	INSERT INTO expected (CITY, STATE) select 'Montgomery City','MO'
	INSERT INTO expected (CITY, STATE) select 'Delavan','MN'
	INSERT INTO expected (CITY, STATE) select 'Magnolia','MS'
	INSERT INTO expected (CITY, STATE) select 'Byron','CA'
	INSERT INTO expected (CITY, STATE) select 'Dundee','IA'
	INSERT INTO expected (CITY, STATE) select 'Eureka Springs','AR'
	INSERT INTO expected (CITY, STATE) select 'Baker','CA'
	INSERT INTO expected (CITY, STATE) select 'Hyde Park','MA'
	INSERT INTO expected (CITY, STATE) select 'Groveoak','AL'
	INSERT INTO expected (CITY, STATE) select 'Kenner','LA'
	INSERT INTO expected (CITY, STATE) select 'Many','LA'
	INSERT INTO expected (CITY, STATE) select 'Seward','AK'
	INSERT INTO expected (CITY, STATE) select 'Berryton','KS'
	INSERT INTO expected (CITY, STATE) select 'Chilhowee','MO'
	INSERT INTO expected (CITY, STATE) select 'Newark','IL'
	INSERT INTO expected (CITY, STATE) select 'Cowgill','MO'
	INSERT INTO expected (CITY, STATE) select 'Novinger','MO'
	INSERT INTO expected (CITY, STATE) select 'Goodman','MS'
	INSERT INTO expected (CITY, STATE) select 'Cobalt','CT'
	INSERT INTO expected (CITY, STATE) select 'South Haven','MI'
	INSERT INTO expected (CITY, STATE) select 'Eskridge','KS'
	INSERT INTO expected (CITY, STATE) select 'Bennington','KS'
	INSERT INTO expected (CITY, STATE) select 'Decatur','MS'
	INSERT INTO expected (CITY, STATE) select 'West Hyannisport','MA'
	INSERT INTO expected (CITY, STATE) select 'Ozona','FL'
	INSERT INTO expected (CITY, STATE) select 'Jackson','AL'
	INSERT INTO expected (CITY, STATE) select 'Lapeer','MI'
	INSERT INTO expected (CITY, STATE) select 'Peaks Island','ME'
	INSERT INTO expected (CITY, STATE) select 'Hazlehurst','MS'
	INSERT INTO expected (CITY, STATE) select 'Chester','CA'
	INSERT INTO expected (CITY, STATE) select 'Clarkston','MI'
	INSERT INTO expected (CITY, STATE) select 'Healdsburg','CA'
	INSERT INTO expected (CITY, STATE) select 'Hotchkiss','CO'
	INSERT INTO expected (CITY, STATE) select 'Ravenden Springs','AR'
	INSERT INTO expected (CITY, STATE) select 'Monroe','AR'
	INSERT INTO expected (CITY, STATE) select 'Payson','IL'
	INSERT INTO expected (CITY, STATE) select 'Kell','IL'
	INSERT INTO expected (CITY, STATE) select 'Strasburg','CO'
	INSERT INTO expected (CITY, STATE) select 'Five Points','AL'
	INSERT INTO expected (CITY, STATE) select 'Norris City','IL'
	INSERT INTO expected (CITY, STATE) select 'Coaling','AL'
	INSERT INTO expected (CITY, STATE) select 'Orange City','IA'
	INSERT INTO expected (CITY, STATE) select 'Effingham','KS'
	INSERT INTO expected (CITY, STATE) select 'Corcoran','CA'
	INSERT INTO expected (CITY, STATE) select 'Garden City','IA'
	INSERT INTO expected (CITY, STATE) select 'Alton','MO'
	INSERT INTO expected (CITY, STATE) select 'Greenway','AR'
	INSERT INTO expected (CITY, STATE) select 'Woodsboro','MD'
	INSERT INTO expected (CITY, STATE) select 'Strawn','IL'
	INSERT INTO expected (CITY, STATE) select 'Dent','MN'
	INSERT INTO expected (CITY, STATE) select 'Shingletown','CA'
	INSERT INTO expected (CITY, STATE) select 'Clio','IA'
	INSERT INTO expected (CITY, STATE) select 'Yalaha','FL'
	INSERT INTO expected (CITY, STATE) select 'Leakesville','MS'
	INSERT INTO expected (CITY, STATE) select 'Fort Lupton','CO'
	INSERT INTO expected (CITY, STATE) select 'Shasta','CA'
	INSERT INTO expected (CITY, STATE) select 'Canton','MN'
	INSERT INTO expected (CITY, STATE) select 'Agency','MO'
	INSERT INTO expected (CITY, STATE) select 'South Carrollton','KY'
	INSERT INTO expected (CITY, STATE) select 'Taft','CA'
	INSERT INTO expected (CITY, STATE) select 'Calpine','CA'
	INSERT INTO expected (CITY, STATE) select 'Knobel','AR'
	INSERT INTO expected (CITY, STATE) select 'Bullhead City','AZ'
	INSERT INTO expected (CITY, STATE) select 'Tina','MO'
	INSERT INTO expected (CITY, STATE) select 'Anthony','KS'
	INSERT INTO expected (CITY, STATE) select 'Emmett','ID'
	INSERT INTO expected (CITY, STATE) select 'South Haven','MN'
	INSERT INTO expected (CITY, STATE) select 'Haverhill','IA'
	INSERT INTO expected (CITY, STATE) select 'Middleboro','MA'
	INSERT INTO expected (CITY, STATE) select 'Siloam','GA'
	INSERT INTO expected (CITY, STATE) select 'Lena','LA'
	INSERT INTO expected (CITY, STATE) select 'Lee','IL'
	INSERT INTO expected (CITY, STATE) select 'Freeport','MI'
	INSERT INTO expected (CITY, STATE) select 'Mid Florida','FL'
	INSERT INTO expected (CITY, STATE) select 'Acme','LA'
	INSERT INTO expected (CITY, STATE) select 'Gorham','KS'
	INSERT INTO expected (CITY, STATE) select 'Bass Harbor','ME'
	INSERT INTO expected (CITY, STATE) select 'Granger','IA'

    EXEC tSQLt.AssertEqualsTable 'expected', 'actual';

END;

GO

--exec tSQLt.Run 'BasicSelectTestClass.[test_07wos01]';